sherlockode_acb_content_create:
    path: /mycontent/create
    defaults: { _controller: sherlockode_advanced_content.controller.content:createAction }

sherlockode_acb_content_create_by_type:
    path: /mycontent/create/{id}
    defaults: { _controller: sherlockode_advanced_content.controller.content:createByTypeAction }

sherlockode_acb_content_list:
    path: /mycontent/list/
    defaults: { _controller: sherlockode_advanced_content.controller.content:listAction }

sherlockode_acb_content_edit:
    path: /mycontent/edit/{id}
    defaults: { _controller: sherlockode_advanced_content.controller.content:editAction }

sherlockode_acb_content_delete:
    path: /mycontent/delete/{id}
    defaults: { _controller: sherlockode_advanced_content.controller.content:deleteAction }

sherlockode_acb_content_view:
    path: /mycontent/view/{id}
    defaults: { _controller: sherlockode_advanced_content.controller.content:viewAction }

sherlockode_acb_content_type_edit:
    path: /mycontent-type/edit/{id}
    defaults: { _controller: sherlockode_advanced_content.controller.content_type:editAction }

sherlockode_acb_content_type_create:
    path: /mycontent-type/create
    defaults: { _controller: sherlockode_advanced_content.controller.content_type:createAction }

sherlockode_acb_content_type_delete:
    path: /mycontent-type/delete/{id}
    defaults: { _controller: sherlockode_advanced_content.controller.content_type:deleteAction }

sherlockode_acb_content_type_add_field:
    path: /mycontent-type/add-field/{contentTypeId}
    defaults: { _controller: sherlockode_advanced_content.controller.content_type:addFieldAction }

sherlockode_acb_content_type_change_field_type:
    path: /mycontent-type/change-field-type
    defaults: { _controller: sherlockode_advanced_content.controller.content_type:changeFieldTypeAction }

sherlockode_acb_content_type_list:
    path: /mycontent-type/list
    defaults: { _controller: sherlockode_advanced_content.controller.content_type:listAction }
