services:
    _defaults:
        autowire: true

    Sherlockode\AdvancedContentBundle\Manager\:
        resource: '../../Manager/*'
    Sherlockode\AdvancedContentBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
