services:
    sherlockode_advanced_content.form_builder_manager:
        class: Sherlockode\AdvancedContentBundle\Manager\FormBuilderManager
        arguments:
            - '@sherlockode_advanced_content.content_manager'
            - '@sherlockode_advanced_content.field_manager'
            - '@sherlockode_advanced_content.configuration_manager'
            - '@sherlockode_advanced_content.content_type_manager'

    sherlockode_advanced_content.content_manager:
        class: Sherlockode\AdvancedContentBundle\Manager\ContentManager
        arguments:
            - '@sherlockode_advanced_content.configuration_manager'
            - '@doctrine.orm.entity_manager'

    sherlockode_advanced_content.content_type_manager:
        class: Sherlockode\AdvancedContentBundle\Manager\ContentTypeManager
        arguments:
            - '@sherlockode_advanced_content.configuration_manager'
            - '@doctrine.orm.entity_manager'

    sherlockode_advanced_content.configuration_manager:
        class: Sherlockode\AdvancedContentBundle\Manager\ConfigurationManager

    sherlockode_advanced_content.field_manager:
        class: Sherlockode\AdvancedContentBundle\Manager\FieldManager

    sherlockode_advanced_content.upload_manager:
        class: Sherlockode\AdvancedContentBundle\Manager\UploadManager
        arguments: [~, ~]

    sherlockode_advanced_content.form.field:
        class: Sherlockode\AdvancedContentBundle\Form\Type\FieldType
        arguments:
            - '@sherlockode_advanced_content.field_manager'
        tags:
            - {name: form.type }

    sherlockode_advanced_content.content_extension:
        class: Sherlockode\AdvancedContentBundle\Twig\Extension\ContentExtension
        arguments:
            - '@sherlockode_advanced_content.field_manager'
        tags: ['twig.extension']

    sherlockode_advanced_content.field_value_listener:
        class: Sherlockode\AdvancedContentBundle\EventListener\FieldValueListener
        arguments:
            - '@sherlockode_advanced_content.field_manager'
        tags:
            - { name: doctrine.event_listener, event: preUpdate, lazy: true }
