Sherlockode\AdvancedContentBundle\Model\Field:
  type: mappedSuperclass
  fields:
    type:
      type: string
    name:
      type: string
    slug:
      type: string
    required:
      type: boolean
      column: is_required
      nullable: false
      options:
        default: false
    options:
      type: string
      nullable: true
    sortOrder:
      type: integer
      column: sort_order
      options:
        default: 0
    hint:
      type: string
      nullable: true
