Sherlockode\AdvancedContentBundle\Model\Field:
  type: mappedSuperclass
  fields:
    type:
      type: string
    name:
      type: string
    slug:
      type: string
      gedmo:
        slug:
          separator: _
          updatable: true
          fields:
            - name
    isRequired:
      type: boolean
      column: is_required
      nullable: false
      options:
        default: false
    options:
      type: string
      nullable: true
    sortOrder:
      type: integer
      column: sort_order
      options:
        default: 0
